{{- if .Values.azure.workloadIdentity.enabled }}

apiVersion: v1

kind: ServiceAccount

metadata:

  name: {{ include "backend-stack.serviceAccountName" . }}

  labels:
    {{- include "backend-stack.labels" . | nindent 4 }}

  annotations:

    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentity.clientId | quote }}

{{- end }}