
name: Deploy Microservices

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

permissions:
  id-token: write
  contents: read

env:
  HELM_RELEASE: backend-stack
  CHART_PATH: ./backend-stack
  K8S_NAMESPACE: backend-${{ inputs.environment }}

jobs:

  deploy:

    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:

      # -----------------------------
      # Checkout repository
      # -----------------------------

      - name: Checkout code
        uses: actions/checkout@v4


      # -----------------------------
      # Azure Login
      # -----------------------------

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      # -----------------------------
      # AKS Credentials
      # -----------------------------

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group dev-nitor-rg-002 \
            --name dev-nitor-cluster-01 \
            --overwrite-existing


      # -----------------------------
      # Setup Helm
      # -----------------------------

      - name: Setup Helm
        uses: azure/setup-helm@v4


      # -----------------------------
      # Helm Dependencies
      # -----------------------------

      - name: Update Helm dependencies
        working-directory: ${{ env.CHART_PATH }}
        run: |
          helm dependency update .


      # -----------------------------
      # Helm Lint
      # -----------------------------

      - name: Helm lint
        working-directory: ${{ env.CHART_PATH }}
        run: |
          helm lint . \
            -f "values/${{ inputs.environment }}-values.yaml"


      # -----------------------------
      # Create Namespace
      # -----------------------------

      - name: Create namespace
        run: |
          kubectl create namespace ${{ env.K8S_NAMESPACE }} \
            --dry-run=client \
            -o yaml | kubectl apply -f -


      # -----------------------------
      # Deploy
      # -----------------------------

      - name: Deploy Helm chart
        working-directory: ${{ env.CHART_PATH }}
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE }} . \
            --namespace ${{ env.K8S_NAMESPACE }} \
            --create-namespace \
            -f "values/${{ inputs.environment }}-values.yaml" \
            --wait \
            --timeout 10m


      # -----------------------------
      # Deployment status
      # -----------------------------

      - name: Check deployment
        run: |

          echo "Environment: ${{ inputs.environment }}"
          echo "Namespace: ${{ env.K8S_NAMESPACE }}"

          kubectl get pods \
            -n ${{ env.K8S_NAMESPACE }}

          kubectl get svc \
            -n ${{ env.K8S_NAMESPACE }}

          kubectl get ingress \
            -n ${{ env.K8S_NAMESPACE }}

